quad:
  
  left_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: FL_upright_joint
    pid: {p: 500.0, i: 10.0, d: 100.0}
    

  left_front_axle_controller:
##    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: FL_wheel_joint
    pid: {p: 1500.0, i: 100.0, d: 750.0}

  right_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: FR_upright_joint
    pid: {p: 500.0, i: 10.0, d: 100.0}
    
  right_front_axle_controller:
##    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: FR_wheel_joint
    pid: {p: 1500.0, i: 100.0, d: 750.0}

  # traction
  left_rear_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: RL_wheel_joint
    pid: {p: 1500.0, i: 100.0, d: 750.0}

  # traction
  right_rear_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: RR_wheel_joint
    pid: {p: 1500.0, i: 100.0, d: 750.0}
        
  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 50.0
